/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bancos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tudo o que a app precisa para montar o formulário adaptativo.
         * @description É a única fonte desta informação — a app não tem listas de bancos escritas à mão.
         */
        get: operations["listarBancos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compara as ofertas dos bancos escolhidos. Síncrono.
         * @description ⚠️ Responde de uma vez, com estatuto 200. Não há trabalho em segundo plano, identificador para sondar, nem estado `em_curso` — e a diferença não é de estilo. Desde a inversão da §1 do ARQUITETURA.md (2026-07-25) uma comparação NÃO fala com banco nenhum: lê a série varrida em hora morta e calcula localmente. Custa uma consulta e aritmética, e não as dezenas de segundos de scraping que justificavam o 202 e a sondagem.
         *     ⚠️ Nada do pedido é persistido (§7.5, e a postura pública do README): não há recurso a que voltar, e é por isso que não existe `GET /api/v1/comparacoes/{id}`. Poder sondar uma resposta obrigaria a guardar o pedido que a gerou — que é precisamente o dado pessoal que este serviço se recusa a ter. A ausência da rota é a decisão, não uma lacuna.
         *     ⚠️ A `taeg` e o `mtic` de cada oferta são DERIVADOS, não medidos, e cada oferta declara em `pressupostos` sobre que hipóteses. Ver o schema da Oferta.
         */
        post: operations["compararOfertas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rate-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ⚠️ CONGELADA — a série de mercado, compatível ao byte com o v1.
         * @description Consumida em produção pelo viabilidade-imobiliaria (src/viabilidade/taxas.py). Nomes em inglês e snake_case, ao contrário do resto do repositório. Três armadilhas de compatibilidade, todas cobertas pelo teste de contrato contra uma amostra real do v1: (1) números, não strings — a serialização de decimais em Go põe aspas por omissão, e aqui a saída é `number`; (2) `captured_at` sem fuso — o v1 serializava instantes ingénuos (`2026-07-22T05:00:11`, sem Z); este endpoint replica o formato antigo, por isso é `string` e não `date-time`; (3) `products` é sempre lista, nunca null. Sem `X-API-Key` configurada o endpoint fica aberto — comportamento de desenvolvimento, com aviso alto no arranque.
         */
        get: operations["obterRateCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rate-catalog/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ⚠️ CONGELADA — os varrimentos disponíveis, com contagem de linhas. */
        get: operations["listarSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sondagem de saúde trivial para a plataforma. */
        get: operations["saude"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BancosResposta: {
            bancos: components["schemas"]["Banco"][];
            inputs_canonicos: components["schemas"]["InputCanonico"][];
        };
        Banco: {
            /** @example novobanco */
            id: string;
            /** @example Novo Banco */
            nome: string;
            inputs: components["schemas"]["BancoInput"][];
            periodos_fixos: number[];
            /** @enum {string} */
            periodos_fixos_modo: "lista" | "da-api" | "do-html";
            /**
             * @description Vazio não é «não sei» — é «o banco impõe o seu e ignora a escolha».
             * @example [
             *       "3m",
             *       "6m",
             *       "12m"
             *     ]
             */
            euribor_opcoes: string[];
            /** @description Quando não-nulo, o banco impõe este indexante. */
            euribor_imposto: string | null;
            prazo_min: number;
            prazo_max: number;
            idade_maxima_fim: number;
            produtos: components["schemas"]["Produto"][];
            notas: string[];
        };
        BancoInput: {
            /** @example valor_imovel */
            chave: string;
            usa: boolean;
            /** @description Presente quando ajuda a explicar porque o banco não usa o campo. */
            nota?: string;
        };
        Produto: {
            /** @example novobanco:primeiro_banco */
            id: string;
            rotulo: string;
            descricao: string;
            por_omissao: boolean;
        };
        InputCanonico: {
            /** @example valor_imovel */
            chave: string;
            /** @example Valor do imóvel */
            rotulo: string;
            /** @example dinheiro */
            tipo: string;
        };
        ComparacaoPedido: {
            /**
             * @example [
             *       "cgd",
             *       "novobanco",
             *       "montepio",
             *       "bancoctt"
             *     ]
             */
            bancos: string[];
            pedido: components["schemas"]["Pedido"];
            /** @description Produtos escolhidos por banco. Chave = id do banco. */
            produtos?: {
                [key: string]: string[];
            };
        };
        Pedido: {
            /** Format: double */
            valor_imovel: number;
            /** Format: double */
            montante: number;
            prazo_anos: number;
            /** @enum {string} */
            rate_type: "variavel" | "fixa" | "mista";
            /** @description Anos de período fixo; aplica-se a `fixa` e `mista`. */
            fixed_period_years?: number;
            /** @enum {string} */
            euribor_indexante?: "3m" | "6m" | "12m";
            titulares: components["schemas"]["Titular"][];
            /** @enum {string} */
            finalidade: "propria" | "secundaria" | "arrendamento";
            /** @example continente */
            localizacao: string;
            garantia_publica?: boolean;
            ja_cliente?: boolean;
        };
        Titular: {
            /**
             * Format: date
             * @example 1990-04-12
             */
            data_nascimento: string;
            /** Format: double */
            rendimento_mensal: number;
        };
        /**
         * @description O resultado completo, de uma vez.
         *     ⚠️ Não tem `id`, `estado` nem `progresso`, e nenhum dos três falta por esquecimento — a resposta É o cálculo inteiro, e não o primeiro estado de um trabalho que continua. Estavam aqui um `SimulacaoCriada` (`{id, estado, bancos, duracao_estimada_s}`) e um `Simulacao` com `estado: em_curso | terminado` e `progresso: {prontos, total}`: existiam para a app desenhar uma barra enquanto se falava com os bancos. Já não se fala com os bancos no caminho do cliente, e uma barra de progresso sobre uma consulta a Postgres seria teatro.
         *     ⚠️ Também não tem `pedido_efectivo`. Aquele campo trazia `{montante, valor_imovel, quantizado}` porque a cache quantizava o montante para partilhar entradas entre pedidos parecidos, e a app tinha de mostrar o valor efectivamente simulado em vez do pedido. Sem cache não há quantização: o cálculo usa o montante que foi pedido, ao cêntimo. O que um banco ajusta (prazo, período fixo, indexante) continua a viajar em `Oferta.aplicado`, com a nota obrigatória agarrada — por banco, que é onde o ajuste acontece, e não num campo global que fingia valer para todos.
         */
        Comparacao: {
            /**
             * Format: date-time
             * @description Quando ESTA resposta foi calculada.
             *     ⚠️ Não é o `capturado_em` de cada oferta, que é quando o preço foi medido no banco. Os dois são diferentes por construção, e é precisamente essa diferença que diz à pessoa a idade do preço que está a ver — por isso viajam os dois, e por isso nenhum deles é opcional numa oferta com sucesso.
             */
            calculado_em: string;
            ofertas: components["schemas"]["Oferta"][];
        };
        /** @description ⚠️ Quando `aplicado` não está vazio, os números não correspondem ao pedido — a app é obrigada a mostrar a nota junto do valor. `erro` só aparece quando `sucesso` é falso. */
        Oferta: {
            banco_id: string;
            banco_nome: string;
            sucesso: boolean;
            /**
             * Format: double
             * @description Spread do degrau de LTV que contém o rácio pedido, mais a Euribor do tenor aplicável — ambos medidos. Na fixa e na mista, a taxa da fase fixa é a observação do período que o banco pratica.
             */
            tan?: number;
            /**
             * Format: double
             * @description ⚠️ Do INTERVALO de LTV medido que contém o rácio pedido, e não de uma banda assumida. Num degrau que não se conseguiu resolver é o lado mais CARO do intervalo (Directiva 2014/17/UE, Anexo I, Parte II, alínea (d)), e `notas` traz a frase que nomeia os dois lados.
             */
            spread?: number;
            /**
             * Format: double
             * @description Amortização francesa sobre a `tan` e o montante pedido. É aritmética exacta, não medição — e é por isso que responde ao montante desta pessoa, e não ao do cenário de referência.
             */
            prestacao_mensal?: number;
            /**
             * Format: double
             * @description ⚠️ DERIVADA, não medida. Ver `pressupostos`, que é obrigatório sempre que este campo vem preenchido.
             *     A TAEG depende dos encargos (comissões, imposto, seguros) e o seguro de vida depende de quem pede — e a série de mercado é varrida com um titular NEUTRO e fictício, sobre um cenário de referência fixo (§4). Não existe, portanto, TAEG medida para esta pessoa. O que se faz é atribuir a encargos a diferença entre a TAEG e a TAN observadas no ponto de referência, e reamortizar sobre os fluxos deste pedido.
             *     ⚠️ A repartição desses encargos entre comissões, imposto e seguro NÃO está medida: é inferida. Quem lê este número tem de o tratar como indicativo, e a app é obrigada a mostrar `pressupostos` junto dele — é o que o Anexo I e o Anexo II da MCD mandam fazer a um valor que depende de hipóteses declaradas.
             */
            taeg?: number;
            /**
             * Format: double
             * @description ⚠️ DERIVADO, pela mesma razão e sobre o mesmo modelo de encargos que a `taeg`. Ver `pressupostos`.
             */
            mtic?: number;
            /**
             * @description As hipóteses sob as quais a `taeg` e o `mtic` desta oferta foram derivados, em português e legíveis por uma pessoa.
             *     ⚠️ Lista à parte de `notas`, e não misturada nela, de propósito: as duas têm estatutos diferentes. Uma `nota` é um aviso sobre o que aconteceu a ESTE pedido — o banco encurtou o prazo, o degrau de LTV não estava resolvido. Um pressuposto é uma hipótese de cálculo que a MCD obriga a declarar junto do número que dela depende (Anexo I, Parte II; Anexo II). Empacotadas na mesma lista, a app ficava sem forma de as apresentar como o que são.
             *     ⚠️ Não vazia sempre que `taeg` ou `mtic` vêm preenchidos. Vazia com um deles preenchido é defeito nosso, e não um caso legítimo.
             */
            pressupostos?: string[];
            euribor_indexante?: string;
            /** Format: double */
            euribor_valor?: number;
            fases?: components["schemas"]["Fase"][];
            produtos_aplicados?: string[];
            /** @description O que o banco usou de facto, quando difere do pedido. Vazio = igual ao pedido. */
            aplicado?: {
                [key: string]: unknown;
            };
            notas?: string[];
            /**
             * Format: date-time
             * @description Quando o preço foi MEDIDO no banco, durante o varrimento — não quando esta resposta foi calculada (isso é o `calculado_em` da Comparacao).
             *     ⚠️ Presente sempre que `sucesso` é verdadeiro, e é o campo mais importante desta lista para a honestidade do produto: é o único que diz à pessoa que está a ver um preço de ontem à noite e não de agora. A app é obrigada a mostrá-lo. Escondê-lo apresentaria dados varridos como se fossem uma consulta ao vivo ao banco, que é exactamente o que este serviço não faz.
             */
            capturado_em?: string;
            erro?: components["schemas"]["OfertaErro"];
        };
        Fase: {
            ate_mes: number;
            /** Format: double */
            taxa: number;
            /** Format: double */
            prestacao: number;
        };
        /** @description Estruturado de propósito: `codigo` é para a app decidir, `mensagem` é para a pessoa ler, em português. */
        OfertaErro: {
            /** @example prazo_impossivel */
            codigo: string;
            mensagem: string;
        };
        RespostaErro: {
            erro: components["schemas"]["DetalheErro"];
            request_id?: string;
        };
        DetalheErro: {
            /** @example pedido_invalido */
            codigo: string;
            mensagem: string;
            /** @description O campo que falhou, quando aplicável. */
            campo?: string;
        };
        Saude: {
            /** @example ok */
            estado: string;
        };
        RateCatalog: {
            scenarios: components["schemas"]["Scenario"][];
            count: number;
            points: components["schemas"]["Point"][];
        };
        Scenario: {
            /** @example ltv80_mista_30a */
            key: string;
            /** @example LTV 80% · mista · 30 anos */
            label: string;
            /** Format: double */
            ltv: number;
            /** Format: double */
            valor_imovel: number;
            /** Format: double */
            montante: number;
            prazo_anos: number;
            rate_type: string;
            /** @description ⚠️ **Nulo na taxa variável**, e é assim que o v1 o envia — medido a 2026-07-28 contra o v1 a correr. Um inteiro não-nulo em Go serializa `0`, e o `viabilidade-imobiliaria` receberia zero anos de período fixo onde espera «não se aplica». */
            fixed_period_years: number | null;
        };
        /** @description ⚠️ `captured_at` é `string` (sem fuso, formato v1) de propósito. `products` é sempre lista, nunca null. Os números são `number`, não string. */
        Point: {
            snapshot_id: string;
            /**
             * @description ⚠️ Sem fuso, formato v1 (ex.: 2026-07-22T05:00:11). NÃO é date-time.
             * @example 2026-07-22T05:00:11
             */
            captured_at: string;
            scenario_key: string;
            bank_id: string;
            bank_name: string;
            rate_type: string;
            /** Format: double */
            valor_imovel: number;
            /** Format: double */
            montante: number;
            prazo_anos: number;
            /** @description ⚠️ Nulo na taxa variável, como o v1 o envia. Ver o Scenario. */
            fixed_period_years: number | null;
            /** Format: double */
            tan: number;
            /** Format: double */
            taeg: number;
            /** Format: double */
            spread: number;
            /** Format: double */
            prestacao_mensal: number;
            /** Format: double */
            mtic: number;
            euribor_indexante: string;
            /** Format: double */
            euribor_valor: number;
            products: string[];
        };
        SnapshotsResposta: {
            snapshots: components["schemas"]["Snapshot"][];
        };
        Snapshot: {
            snapshot_id: string;
            /** @description ⚠️ Sem fuso, formato v1. */
            captured_at: string;
            rows: number;
        };
    };
    responses: {
        /** @description Pedido inválido, com o campo nomeado. */
        PedidoInvalido: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespostaErro"];
            };
        };
        /**
         * @description Tecto de pedidos por IP excedido.
         *     ⚠️ A razão mudou com a inversão da §1, e o tecto não. Existia porque cada submissão custava dezenas de segundos de scraping a partir do NOSSO IP contra os bancos — hoje custa uma consulta, e essa justificação caiu. Fica por outra, ordinária e suficiente: isto é JSON público e um tecto é o que impede um cliente avariado de esgotar o pool de ligações dos outros. É o mesmo endpoint e um limiar muito mais alto; o que não se faz é apagar o tecto por a primeira razão ter deixado de valer.
         */
        TectoExcedido: {
            headers: {
                /** @description Segundos a esperar antes de repetir. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespostaErro"];
            };
        };
        /**
         * @description Não há série de mercado que responda a este pedido: nenhum dos bancos escolhidos tem observações utilizáveis.
         *     ⚠️ Substitui o `DemasiadasEmCurso` do modelo ao vivo, e não é o mesmo 503. Aquele dizia «estamos ocupados a falar com os bancos, volta»; este diz «o varrimento ainda não correu, ou correu e falhou para estes bancos». O primeiro resolvia-se esperando; este resolve-se correndo `simulador varrer` — e é por isso que a mensagem tem de os distinguir em vez de os empacotar num «tenta mais tarde».
         */
        SerieIndisponivel: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespostaErro"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listarBancos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A lista de bancos e os inputs canónicos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BancosResposta"];
                };
            };
        };
    };
    compararOfertas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparacaoPedido"];
            };
        };
        responses: {
            /** @description As ofertas calculadas a partir da série de mercado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparacao"];
                };
            };
            400: components["responses"]["PedidoInvalido"];
            429: components["responses"]["TectoExcedido"];
            503: components["responses"]["SerieIndisponivel"];
        };
    };
    obterRateCatalog: {
        parameters: {
            query?: {
                scenario?: string;
                bank?: string;
                rate_type?: string;
                /** @description Instante ISO 8601; devolve pontos capturados a partir daqui. */
                since?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cenários de referência e os pontos de mercado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateCatalog"];
                };
            };
        };
    };
    listarSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A lista de snapshots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotsResposta"];
                };
            };
        };
    };
    saude: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O serviço está de pé. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saude"];
                };
            };
        };
    };
}
