/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bancos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tudo o que a app precisa para montar o formulário adaptativo.
         * @description É a única fonte desta informação — a app não tem listas de bancos escritas à mão.
         */
        get: operations["listarBancos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ofertas/{banco}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pergunta a UM banco o preço do crédito descrito. Ao vivo.
         * @description Vai ao simulador público do banco com os valores que a pessoa introduziu e devolve o que ele respondeu. Demora o que o banco demorar, com um prazo nosso por cima.
         *
         *     ⚠️ É POST e não GET porque o pedido leva data de nascimento e rendimento: num GET isso viajava na query string, e ficava no histórico do browser, nos logs de qualquer proxy pelo caminho e no Referer.
         *
         *     ⚠️ Um banco que não responde a tempo NÃO é um erro deste pedido: a resposta é 200 com a oferta em falha e o código `banco_indisponivel`. Quem falhou foi o banco, e a app põe uma linha com ele nomeado em vez de um ecrã de erro.
         */
        post: operations["ofertaDeUmBanco"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sondagem de saúde trivial para a plataforma. */
        get: operations["saude"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BancosResposta: {
            bancos: components["schemas"]["Banco"][];
            inputs_canonicos: components["schemas"]["InputCanonico"][];
        };
        Banco: {
            /** @example novobanco */
            id: string;
            /** @example Novo Banco */
            nome: string;
            inputs: components["schemas"]["BancoInput"][];
            periodos_fixos: number[];
            /** @enum {string} */
            periodos_fixos_modo: "lista" | "da-api" | "do-html";
            /**
             * @description Vazio não é «não sei» — é «o banco impõe o seu e ignora a escolha».
             * @example [
             *       "3m",
             *       "6m",
             *       "12m"
             *     ]
             */
            euribor_opcoes: string[];
            /** @description Quando não-nulo, o banco impõe este indexante. */
            euribor_imposto: string | null;
            prazo_min: number;
            prazo_max: number;
            idade_maxima_fim: number;
            produtos: components["schemas"]["Produto"][];
            notas: string[];
        };
        BancoInput: {
            /** @example valor_imovel */
            chave: string;
            usa: boolean;
            /** @description Presente quando ajuda a explicar porque o banco não usa o campo. */
            nota?: string;
        };
        Produto: {
            /** @example novobanco:primeiro_banco */
            id: string;
            rotulo: string;
            descricao: string;
            por_omissao: boolean;
        };
        InputCanonico: {
            /** @example valor_imovel */
            chave: string;
            /** @example Valor do imóvel */
            rotulo: string;
            /** @example dinheiro */
            tipo: string;
        };
        /** @description O pedido para UM banco. Não leva lista de bancos: o banco vem no caminho, e os produtos são só os desse banco. */
        OfertaPedido: {
            pedido: components["schemas"]["Pedido"];
            /** @description Ids dos produtos escolhidos deste banco. */
            produtos?: string[];
        };
        Pedido: {
            /** Format: double */
            valor_imovel: number;
            /** Format: double */
            montante: number;
            prazo_anos: number;
            /** @enum {string} */
            rate_type: "variavel" | "fixa" | "mista";
            /** @description Anos de período fixo; aplica-se a `fixa` e `mista`. */
            fixed_period_years?: number;
            /** @enum {string} */
            euribor_indexante?: "3m" | "6m" | "12m";
            titulares: components["schemas"]["Titular"][];
            /** @enum {string} */
            finalidade: "propria" | "secundaria" | "arrendamento";
            /** @example continente */
            localizacao: string;
            garantia_publica?: boolean;
            ja_cliente?: boolean;
        };
        Titular: {
            /**
             * Format: date
             * @example 1990-04-12
             */
            data_nascimento: string;
            /** Format: double */
            rendimento_mensal: number;
        };
        /** @description ⚠️ Quando `aplicado` não está vazio, os números não correspondem ao pedido — a app é obrigada a mostrar a nota junto do valor. `erro` só aparece quando `sucesso` é falso. */
        Oferta: {
            banco_id: string;
            banco_nome: string;
            sucesso: boolean;
            /**
             * Format: double
             * @description A TAN que o banco devolveu para este pedido.
             */
            tan?: number;
            /**
             * Format: double
             * @description O spread que o banco aplicou a este pedido. ⚠️ Não é uma banda assumida nem um intervalo por resolver: é o número que ele devolveu, para o rácio de financiamento que esta pessoa pediu.
             */
            spread?: number;
            /**
             * Format: double
             * @description A prestação mensal que o banco devolveu para este pedido.
             */
            prestacao_mensal?: number;
            /**
             * Format: double
             * @description A TAEG que o simulador do banco devolveu.
             *     ⚠️ **Cotada por ele, e não derivada por nós.** Dizia aqui «DERIVADA, não medida», e era verdade enquanto os preços vinham da série varrida. Deixou de ser a 2026-08-06.
             *     ⚠️ Continua a NÃO ser a TAEG que vincula alguém: essa vem na ficha de informação normalizada, depois de o banco avaliar quem pede. É a distinção que a app é obrigada a mostrar — mas é uma distinção entre simulação e proposta, não entre medido e estimado.
             */
            taeg?: number;
            /**
             * Format: double
             * @description O MTIC que o simulador do banco devolveu, pela mesma razão que a `taeg`.
             */
            mtic?: number;
            euribor_indexante?: string;
            /** Format: double */
            euribor_valor?: number;
            fases?: components["schemas"]["Fase"][];
            produtos_aplicados?: string[];
            /** @description O que o banco usou de facto, quando difere do pedido. Vazio = igual ao pedido. */
            aplicado?: {
                [key: string]: unknown;
            };
            notas?: string[];
            /**
             * @description Verdadeiro quando esta oferta se serviu da cache (§7.6) em vez de se perguntar ao banco agora.
             *     ⚠️ **Não é o mesmo que `capturado_em`, e nenhum dos dois substitui o outro.** O `capturado_em` diz de QUANDO é o preço, e num acerto de cache é o instante em que se falou com o banco — nunca o de agora. Este diz se ESTE pedido chegou a sair para o banco. Uma oferta fresca e um acerto de um segundo atrás têm `capturado_em` quase igual e `em_cache` diferente.
             *     ⚠️ Ausente vale `false`, e não leva `default:` de propósito: o `openapi-typescript` traduz um campo com omissão para um campo OBRIGATÓRIO no tipo gerado, e a app passaria a afirmar que a resposta traz sempre este campo — que é precisamente o que o `required` diz que não. A regra fica na descrição, onde não mente ao gerador.
             */
            em_cache?: boolean;
            /**
             * Format: date-time
             * @description Quando se falou com o banco — o instante em que este preço foi cotado.
             *     ⚠️ **Não é «agora», e a diferença é a razão de o campo existir.** Num acerto de cache (§7.6) é o instante da ida ao banco que produziu a resposta guardada, e pode ser de há cinco minutos. Numa oferta fresca é de há segundos. Dizia aqui «durante o varrimento», e o varrimento saiu — o que fica é o mesmo compromisso por outro caminho.
             *     ⚠️ Presente sempre que `sucesso` é verdadeiro, e é o campo mais importante desta lista para a honestidade do produto. A app é obrigada a mostrá-lo, e o servidor **recusa servir** uma oferta com preço e sem ele (`traduzir.go`): um preço sem data apresenta-se como se fosse de agora.
             */
            capturado_em?: string;
            erro?: components["schemas"]["OfertaErro"];
        };
        Fase: {
            ate_mes: number;
            /** Format: double */
            taxa: number;
            /** Format: double */
            prestacao: number;
        };
        /** @description Estruturado de propósito: `codigo` é para a app decidir, `mensagem` é para a pessoa ler, em português. */
        OfertaErro: {
            /** @example prazo_impossivel */
            codigo: string;
            mensagem: string;
        };
        RespostaErro: {
            erro: components["schemas"]["DetalheErro"];
            request_id?: string;
        };
        DetalheErro: {
            /** @example pedido_invalido */
            codigo: string;
            mensagem: string;
            /** @description O campo que falhou, quando aplicável. */
            campo?: string;
        };
        Saude: {
            /** @example ok */
            estado: string;
        };
    };
    responses: {
        /**
         * @description A app que pediu é anterior à versão mínima que este servidor serve. Código `versao_demasiado_antiga`.
         *     ⚠️ **426 e não 400:** o pedido está bem formado e o problema é o cliente. Um 400 mandava a app corrigir o corpo, que é a acção errada.
         *     ⚠️ **Só acontece se o servidor tiver `APP_VERSAO_MINIMA` declarada**, e por omissão não tem. Existe desde 2026-08-08, antes de haver qualquer versão publicada, porque acrescentá-lo depois não serve de nada: as versões que precisavam de o entender já teriam saído sem ele.
         */
        VersaoDemasiadoAntiga: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespostaErro"];
            };
        };
        /** @description Pedido inválido, com o campo nomeado. */
        PedidoInvalido: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespostaErro"];
            };
        };
        /**
         * @description Tecto de pedidos por IP excedido.
         *     ⚠️ **É estrutural, e não higiene.** Somos um amplificador: uma comparação a cinco bancos são cinco pedidos aqui e ~10 aos simuladores deles, com origem aparente nossa. Sem este tecto, isto é uma ferramenta de carga contra terceiros com uma app à frente.
         *     ⚠️ Dizia aqui que uma submissão «hoje custa uma consulta». Era verdade entre 2026-07-25 e 2026-08-06, e deixou de ser com a reversão da §1. O tecto fica nos 60/min: uma comparação são 5 pedidos, logo 12 comparações por minuto.
         */
        TectoExcedido: {
            headers: {
                /** @description Segundos a esperar antes de repetir. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespostaErro"];
            };
        };
        /**
         * @description Já vão pedidos nossos a mais em curso contra este banco: o tecto de concorrência por banco está cheio (ARQUITETURA.md §7.2). Código `banco_ocupado`, e a resposta traz `Retry-After`.
         *     ⚠️ **Não confundir com a oferta em falha `banco_indisponivel`**, que vem com 200. Essa diz que o banco não respondeu; esta diz que quem não tem lugar somos nós, e o banco está bem. A distinção é para a app poder voltar a pedir este banco daqui a um instante em vez de o riscar da lista.
         */
        BancoOcupado: {
            headers: {
                /** @description Segundos a esperar antes de voltar a pedir este banco. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RespostaErro"];
            };
        };
    };
    parameters: {
        /**
         * @description A versão da app que está a pedir, em três números.
         *     ⚠️ **Opcional, e tem de continuar a ser.** O alvo web e quem experimenta a API por `curl` não a mandam, e exigi-la seria em si uma mudança que parte o `/api/v1` — que é o que este cabeçalho existe para evitar. Ausente, ou ilegível, serve-se na mesma: o que se recusa é uma versão conhecida e velha, nunca a falta de informação.
         */
        VersaoDaApp: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listarBancos: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description A versão da app que está a pedir, em três números.
                 *     ⚠️ **Opcional, e tem de continuar a ser.** O alvo web e quem experimenta a API por `curl` não a mandam, e exigi-la seria em si uma mudança que parte o `/api/v1` — que é o que este cabeçalho existe para evitar. Ausente, ou ilegível, serve-se na mesma: o que se recusa é uma versão conhecida e velha, nunca a falta de informação.
                 */
                "X-App-Versao"?: components["parameters"]["VersaoDaApp"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A lista de bancos e os inputs canónicos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BancosResposta"];
                };
            };
            426: components["responses"]["VersaoDemasiadoAntiga"];
        };
    };
    ofertaDeUmBanco: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description A versão da app que está a pedir, em três números.
                 *     ⚠️ **Opcional, e tem de continuar a ser.** O alvo web e quem experimenta a API por `curl` não a mandam, e exigi-la seria em si uma mudança que parte o `/api/v1` — que é o que este cabeçalho existe para evitar. Ausente, ou ilegível, serve-se na mesma: o que se recusa é uma versão conhecida e velha, nunca a falta de informação.
                 */
                "X-App-Versao"?: components["parameters"]["VersaoDaApp"];
            };
            path: {
                /** @description O id do banco, como vem em GET /api/v1/bancos. */
                banco: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfertaPedido"];
            };
        };
        responses: {
            /** @description A oferta do banco, ou a recusa dele com o código nomeado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Oferta"];
                };
            };
            400: components["responses"]["PedidoInvalido"];
            /** @description O id não é banco nenhum. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            426: components["responses"]["VersaoDemasiadoAntiga"];
            429: components["responses"]["TectoExcedido"];
            503: components["responses"]["BancoOcupado"];
        };
    };
    saude: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O serviço está de pé. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saude"];
                };
            };
        };
    };
}
